# Generated by Django 4.2.30 on 2026-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_alter_fieldchoice_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('password', 'Password'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('select', 'Select')], max_length=255),
        ),
    ]
